### PR TITLE
added openclip and moved preprocessing code to model creation code

### PR DESCRIPTION
**Pull request by hahahannes**

### CODE REVIEW

**Comment by hahahannes** [comment]
@LukasMut I created a custom model for the offical clip model as well and also put the preprocessing there. I think this might clean up the extractor class a little bit.

**Comment by hahahannes** [comment]
Maybe it would be cleaner to also include the official openai clip package instead of the hard copy of clip? Would add a new dependency though

**Comment by LukasMut** [comment]
Totally agree with your last comment!

**Comment by LukasMut** [comment]
Another comment: we should probably do something along the lines of self.preprocess = self.weights.transforms() for models from torchvision. Otherwise we'd check both self.preprocess and self.weights which seems redundant.

**Pull request merged**
