### PR TITLE
CKA speedups + PyTorch 2.0+ support

### PR DESCRIPTION
**Pull request by LukasMut**
- added support for `torch>=2.0.0` and `torchvision=0.15.*` (fixes issue #165)
- implemented CKA in NumPy and PyTorch (torch is 2x faster than NumPy)
- added CUDA support for CKA in PyTorch (100x faster than CKA in NumPy)
- added new function called `get_cka` where user can set `backend` (`torch` or `numpy`)
- added unbiased CKA variant (from [here](https://github.com/google-research/google-research/blob/master/representation_similarity/Demo.ipynb)) in addition to vanilla CKA

### CODE REVIEW

**Comment by Alxmrphi** [comment]
Just wondering while you're "in the zone" with refactoring CKA, maybe you can add the debiased version of CKA? It's an alteration of HSIC and only a minor change, already given in the PyTorch implementation of Simon's notebook demo: 

https://github.com/google-research/google-research/blob/master/representation_similarity/Demo.ipynb

I have some recent work looking at some issues with the regular formulation of CKA and that the debiased/unbiased version might actually be what people need to be looking at in some cases: 

https://openreview.net/forum?id=E1NRrGtIHG

Super, super busy at the moment otherwise I would add it. I still might, if you can't, but the changes to be made are in the notebook above and should only require an extra parameter to the CKA call.

**Comment by LukasMut** [comment]
> Just wondering while you're "in the zone" with refactoring CKA, maybe you can add the debiased version of CKA? It's an alteration of HSIC and only a minor change, already given in the PyTorch implementation of Simon's notebook demo:
> 
> https://github.com/google-research/google-research/blob/master/representation_similarity/Demo.ipynb
> 
> I have some recent work looking at some issues with the regular formulation of CKA and that the debiased/unbiased version might actually be what people need to be looking at in some cases:
> 
> https://openreview.net/forum?id=E1NRrGtIHG
> 
> Super, super busy at the moment otherwise I would add it. I still might, if you can't, but the changes to be made are in the notebook above and should only require an extra parameter to the CKA call.

Done.

**Comment by Alxmrphi** [comment]
Great! Thanks for adding that. Code looks nice!

**Comment by LukasMut** [comment]
> Great! Thanks for adding that. Code looks nice!

You're welcome. Glad to hear you like the code! Could you approve?

**Review by a1247418 — APPROVED** [review]
Code looks good! I'm only vaguely familiar with CKA, so I might have missed something there.

**Review by jonasd4 — APPROVED** [review]
LGTM!

**Pull request merged**
