### PR TITLE
add Harmonization

### PR DESCRIPTION
**Pull request by candemircan**
Adding a custom `Harmonization` class. The model is explained in  [this paper](https://arxiv.org/abs/2211.04533) and is available under [this repo](https://github.com/serre-lab/harmonization). It is a type of model that gets deep neural networks to rely on similar aspects of images as humans do while doing object recognition.

### CODE REVIEW

**Comment by LukasMut** [comment]
@candemircan Thanks for this PR! I think this will definitely be a useful addition to the current models in `thingsvision`. I know Drew's work quite well. Could you add tests for at least two of the models, and update the `README.md` similarly to how you've already changed the docs? I think you need to rebase before you do any of the above.

**Comment by candemircan** [comment]
hey Lukas :) thanks for the quick response. Just made the changes as you requested. Hope it works out fine!

Best,
Can

**Comment by LukasMut** [comment]
@candemircan, thanks a lot for the changes! Could you rebase one more time and submit the PR again? I had to accept a different PR before I could accept yours.

**Comment by LukasMut** [comment]
Also, could you do me a favor and remove the folder `build/lib` after you've rebased? This folder was accidentally added during the previous PR.

**Comment by LukasMut** [comment]
@candemircan I see that the unittests are not passing. Did you rebase correctly?

**Comment by candemircan** [comment]
@LukasMut I believe I did, but a comma was missing. Now I fixed it. Let's see if it passes now

**Comment by LukasMut** [comment]
@candemircan Unfortunately, the unittests are still failing. I think there's a module missing for one of the harmonization models. Please see yourself when and why the tests are failing.

**Comment by LukasMut** [comment]
@candemircan I see that you've added the module to the `requirements.txt` file, but I am wondering whether it has to be added to the `setup.py` and `environment.yml` files too? Unfortunately, the tests are still failing for some reason. Could you test locally what's going on?

**Comment by LukasMut** [comment]
@candemircan Will you submit a new PR? You could have just pushed another commit to this PR. :)

**Comment by candemircan** [comment]
Hi Lukas,

I’ll push another commit to this PR later :) just closed this for now as it kept running new tests despite me not making any changes yet.

22 Feb 2023 at 16:20 by ***@***.***:

**Comment by LukasMut** [comment]
@candemircan Sounds good to me! I can stop automatic testing for this PR until you push another commit.

**Comment by candemircan** [comment]
Hi again

**Comment by LukasMut** [comment]
@Alxmrphi, do you have any idea what's going on with the mac-os unittests?

**Comment by LukasMut** [comment]
> @Alxmrphi, do you have any idea what's going on with the mac-os unittests?

My gut feeling tells me that it has something to do with the
TensorFlow version, but I am not 100% sure. One could also try to pip install `git+https://github.com/leondgarse/keras_cv_attention_models` rather than `keras_cv_attention_models`.

**Comment by Alxmrphi** [comment]
I'm scratching my head at this one, too. How is it passing the unit tests but not the code coverage? I downloaded and ran the unit tests locally and they fail on the harmonization model tests. Quick fixes to install libraries, more failures in different places. The first hurdle it fails at is not having access to `keras_applications`.

**Comment by candemircan** [comment]
>>
> @candemircan do you use `keras-cv-attention-models` or `keras_cv_attention_models` for installing the module via pip? I think it needs to be the former (although the Harmonization repo uses the latter).
> 

Hi Lukas,

I was using the latter, but you are right that the package is named as the former in pypi. Should I change it and make another commit?

**Comment by LukasMut** [comment]
> > > 
> > 
> > 
> > @candemircan do you use `keras-cv-attention-models` or `keras_cv_attention_models` for installing the module via pip? I think it needs to be the former (although the Harmonization repo uses the latter).
> 
> Hi Lukas,
> 
> I was using the latter, but you are right that the package is named as the former in pypi. Should I change it and make another commit?

@candemircan Let me see whether I can figure this out. I feel like that error is not on our end.

**Comment by LukasMut** [comment]
> I'm scratching my head at this one, too. How is it passing the unit tests but not the code coverage? I downloaded and ran the unit tests locally and they fail on the harmonization model tests. Quick fixes to install libraries, more failures in different places. The first hurdle it fails at is not having access to `keras_applications`.

@Alxmrphi, I see that this error is happening within the harmonization module. See the issue that references this PR.

**Review by andropar — APPROVED** [review]
Same as Lukas, we should wait until we figured out what causes codecov to fail, but the rest of the PR looks fine to me!

**Pull request merged**
