### PR TITLE
Add DINO models and update README

### PR DESCRIPTION
**Pull request by Alxmrphi**
Adds the suite of `DINO` models referenced [here](https://github.com/facebookresearch/dino).
`README` has been updated to reflect the addition of the models.

One small and as-of-yet unresolved issue is that the `xcit` models  expect images on a GPU by default. `torch.hub.load` is lacking the `map_location` argument so a slight workaround is needed to load from the URL directly if we want to mirror functionality with the rest of the models. Basically, it's only if `type` is `vissl` that the data passes through `_download_and_save_model` which maps the location to CPU. If `type` is `hub`, this doesn't happen and for me it caused an error because I'm on a MacBook using `mps` and not `cuda` but I don't **expect it will be a big issue for many** and small update at future date will be sufficient to fix.

I just needed to add the PR for time constraints and get the `DINO` models available and will add another `PR` to fix the other issue in the coming days.

I've tested that features from a randomly chosen layer from each model type correctly extracts and saves features as expected (except for the `xcit` models).

### CODE REVIEW

**Review by jonasd4 — APPROVED** [review]
Added small change to only replace fc layer for ResNet50 and not for the ViTs. Otherwise looks fine!

**Comment by LukasMut** [comment]
If there's nothing else you'd like to change at this point @Alxmrphi, I am fine with accepting this PR. Looks good to me

**Review by LukasMut — APPROVED** [review]

**Comment by Alxmrphi** [comment]
> If there's nothing else you'd like to change at this point @Alxmrphi, I am fine with accepting this PR. Looks good to me

All good for now. Will hopefully get around to ConvNext shortly and a few other bits and pieces :)

**Comment by LukasMut** [comment]
@Alxmrphi, I forgot something: Could you please update the docs as well? So far, I just see that you've added the models to the `README.md`, but they should be included in the docs as well. Also, could you maybe add one of the DINO models to the unittests? One is sufficient. Please do all of this in another PR. Thanks.

**Pull request merged**
