### PR TITLE
74 implement low memory option for feature extraction

### PR DESCRIPTION
**Pull request by andropar**
- `extractor.extract_features()` now takes extra arguments `output_dir` and `save_every`
- if `output_dir` is set, features will be written to disk every `save_every` batches (default: 100)
- iteration across batches was abstracted into base extractor

### CODE REVIEW

**Comment by LukasMut** [comment]
Please add documentation about this in the README.md and the docs. Looks good so far :)

**Comment by andropar** [comment]
Will do after Philipp revamped the docs 👍

**Review by LukasMut — COMMENTED** [review]
Why is the default of `steps` set to 100?

**Comment by andropar** [comment]
I thought about this too, its a tradeoff between batch size, number of batches, number of features and feature size. Maybe we can use some kind of heuristic as a default, e.g. assuming 8GB available RAM and then approximating how much would fit into memory?

**Comment by LukasMut** [comment]
> I thought about this too, its a tradeoff between batch size, number of batches, number of features and feature size. Maybe we can use some kind of heuristic as a default, e.g. assuming 8GB available RAM and then approximating how much would fit into memory?

I like that idea. This sounds reasonable to me. We can probably even assume 16GB of available RAM. Every local machine these days has approx. 16 - 32 GB of RAM. The only problem with that approach might be the variability of the size of the activations across layers (early layers consume substantially more space than later layers). However, it's a trade-off as you've just said. We need to make a choice. I think this is a fine choice.

**Pull request merged**
